site_name: RakStar
nav:
  - Introdução: index.md
  - Primeiros Passos: getting-started.md
theme: shadcn
local: pt_BR
markdown_extensions:
  - pymdownx.blocks.tab:
      alternate_style: true 
  - codehilite
